CREATE TABLE `vctl_user` (
  `user_id` bigint(21) NOT NULL COMMENT 'id',
  `confirm` tinyint(1) DEFAULT '0' COMMENT '账号是否经过用户确认 0-未认证，1-已认证',
  `mobile_no` varchar(22) DEFAULT NULL COMMENT '手机号',
  `passport` varchar(128) NOT NULL COMMENT '账号',
  `create_at` bigint(21) NOT NULL COMMENT '创建时间',
  `ip` varchar(15) DEFAULT NULL COMMENT 'ip',
  `update_at` bigint(21) NOT NULL COMMENT '更新时间',
  `status` int(1) DEFAULT '0' COMMENT '0，正常 ， 1.冻结',
  `las_id` bigint(21) DEFAULT NULL COMMENT 'LPS Authentication Service AccountId',
  `pic_url` varchar(300) DEFAULT NULL COMMENT '头像图片保存地址',
  `real_name` varchar(32) DEFAULT NULL COMMENT '真实姓名',
  `is_temp_account` tinyint(4) DEFAULT NULL COMMENT '是否默认账号',
  `origin` varchar(255) DEFAULT NULL COMMENT '来源',
  `first_login` int(11) DEFAULT NULL COMMENT '首次登陆',
  `password` varchar(100) DEFAULT NULL COMMENT '密码',
  `pinyin` varchar(100) DEFAULT NULL COMMENT '姓名拼音',
  `gender` smallint(6) NOT NULL DEFAULT '0' COMMENT '性别',
  `third_id` varchar(64) DEFAULT NULL COMMENT '第三方uid',
  `oem_tag` varchar(20) DEFAULT NULL COMMENT 'oem tag 标识',
  `tv_mobile` varchar(256) DEFAULT NULL,
  `alias` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `idx_pass` (`passport`),
  UNIQUE KEY `idx_mobile` (`mobile_no`),
  UNIQUE KEY `alias` (`alias`),
  KEY `idx_last` (`las_id`),
  KEY `idx_createtime` (`create_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 